class Mpesa

  require 'net/http'
  require 'net/https'
  require 'uri'
  

  TIMESTAMP = '20180814085620'#Time.now.strftime '%Y%m%d%H%M%S'
  SHORTCODE = '174379'
  PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
  PHONENUMBER = '254711430817'
  CONSUMER_KEY = 'AoX12SIQkaAARWcG85UxvWItMlDbwXk0'
  CONSUMER_SECRET = 'j9kiZOmTuhwpV5v6'
  PASSWORD = "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTgwODE0MDg1NjIw"

  # The password for encrypting the request. This is generated by base64 encoding BusinessShortcode,
  #  Passkey and Timestamp.
  #  
  def initialize(phone_number, amount, description )
    @phone_number = phone_number
    @amount       = amount
    @description  = description
  end

  def phone_number
    @phone_number
  end

  def amount
    @amount
  end

  def description
    @description 
  end

  def phone_number=(newPhone_number)
    @phone_number = newPhone_number
  end

  def amount=(newAmount)
    @amount = newAmount
  end

  def description=(newDesc)
    @description = newDesc
  end


  # def self.request

  #   token  = get_token
  #   uri = URI('https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest')
  #   encode_ready_string = SHORTCODE + PASSKEY + TIMESTAMP
  #   password =  Base64.encode64(encode_ready_string)

  #   http = Net::HTTP.new(uri.host, uri.port)
  #   http.use_ssl = true
  #   http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  #   # puts "********* #{token} ***********"

  #   request = Net::HTTP::Post.new(uri)
  #   request["accept"] = 'application/json'
  #   request["content-type"] = 'application/json'
  #   request["authorization"] = "Bearer #{token}" #'Bearer <KtZ9TVCVQRFwgyc243nbqk00rrFg>'
  #   request.body = "{\"BusinessShortCode\": \"#{SHORTCODE}\",
  #     \"Password\": \"#{PASSWORD}\",
  #     \"Timestamp\": \"#{TIMESTAMP}\",
  #     \"TransactionType\": \"CustomerPayBillOnline\",
  #     \"Amount\": \"1\",
  #     \"PartyA\": \"#{PHONENUMBER}\",
  #     \"PartyB\": \"#{SHORTCODE}\",
  #     \"PhoneNumber\": \"#{PHONENUMBER}\",
  #     \"CallBackURL\": \"https://03fa0165.ngrok.io/api/v1/sms\",
  #     \"AccountReference\": \"ll\",
  #     \"TransactionDesc\": \"Tes\"}"

    
  #     response = http.request(request)
  #     puts request.body
  #     return response
  # end
  # response = http.request(request)
  # puts response.read_body
  # 
  
  def self.get_token
    uri2 = URI('https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials')
     response = ""
     # token = ''
     

    Net::HTTP.start(uri2.host, uri2.port,
      :use_ssl => uri2.scheme == 'https',
      :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|

      request = Net::HTTP::Get.new uri2.request_uri
      request.basic_auth "#{CONSUMER_KEY}", "#{CONSUMER_SECRET}"

      response = http.request request # Net::HTTPResponse object

      # puts response
      puts response.body#.class #[:access_token]  



      # t = response.body.split
      # token = t[2]
      # puts "this is it #{token}"
      # return response
       # = response.body
      # token = response.body[:access_token]  
    end

     # token = response[:access_token]   
     
     # puts t
     s = response.body
     parsed_json = JSON.parse(s)
     token = parsed_json["access_token"]
     puts "This is the access_token === #{token}"
     return token
    
  end

  def request_mpesa_api
    phone_number = self.phone_number
    amount       = self.amount
    description  =  self.description

    token  = Mpesa.get_token
    uri = URI('https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest')
    encode_ready_string = SHORTCODE + PASSKEY + TIMESTAMP
    password =  Base64.encode64(encode_ready_string)

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    # puts "********* #{token} ***********"

    request = Net::HTTP::Post.new(uri)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/json'
    request["authorization"] = "Bearer #{token}" #'Bearer <KtZ9TVCVQRFwgyc243nbqk00rrFg>'
    request.body = "{\"BusinessShortCode\": \"#{SHORTCODE}\",
      \"Password\": \"#{PASSWORD}\",
      \"Timestamp\": \"#{TIMESTAMP}\",
      \"TransactionType\": \"CustomerPayBillOnline\",
      \"Amount\": \"#{amount}\",
      \"PartyA\": \"#{phone_number}\",
      \"PartyB\": \"#{SHORTCODE}\",
      \"PhoneNumber\": \"#{phone_number}\",
      \"CallBackURL\": \"http://159.89.103.53/api/v1/pay/from_mpesa\",
      \"AccountReference\": \"kk\",
      \"TransactionDesc\": \"oo\"}"

    
      response = http.request(request)
      # puts request.body
      return response    
  end
end